name: Git depth
description: Get fetch depth from GitHub context

# behaviour:
# github.event.pull_request.head.sha is always used to detect the PR case.
# Fetch depth is number of commits + 1 (base commit)

runs:
  using: composite
  steps:
    - name: Get commit depth
      shell: bash
      run: |
        if [[ "${{ github.event.pull_request.commits }}" ]]; then
          echo "set FETCH_DEPTH based on github.event.pull_request.commits"
          echo "FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
        elif [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && [[ "${{ github.event.forced }}" == "false" ]]; then
          echo "set FETCH_DEPTH based on github.event.before"
          commits_sha='${{ toJSON(github.event.commits.*.id) }}'
          FETCH_DEPTH=$(( $(jq <<<"$commits_sha" length) + 1 ))
          echo "FETCH_DEPTH=$FETCH_DEPTH" >> $GITHUB_ENV
        else
          echo "setting FETCH_DEPTH as 6 (fallback, either force-push, push-new-branch, or unknown event type)"
          echo "FETCH_DEPTH=6" >> $GITHUB_ENV
          echo "FETCH_DEPTH_FALLBACK=true" >> $GITHUB_ENV
        fi

