name: Git Checkout
description: A git checkout for local runners

inputs:
  repository:
    description: "Repository to checkout"
    default: ${{ github.repository }}
  ref:
    description: "The branch, tag, SHA, or PR number (e.g. 123 or pull/123) to resolve"
    default: ${{ github.event.pull_request.number || github.sha }}
  gh-token:
    description: "GitHub Token"
    default: ${{ github.token }}
  path:
    description: "Path to checkout"
    default: '.'
  lfs:
    description: "Enable Git LFS"
    default: 'false'

outputs:
  pr:
    description: "Pull request number"
    value: ${{ steps.resolve.outputs.pr }}
  head_sha:
    description: "Head commit sha"
    value: ${{ steps.checkout.outputs.head_sha }}
  base_sha:
    description: "Base commit sha"
    value: ${{ steps.checkout.outputs.base_sha }}
  checkout_fail_pr_rebase:
    description: "Set to true if PR rebase failed"
    value: ${{ steps.checkout.outputs.checkout_fail_pr_rebase }}
  checkout_fail_pr_fixup:
    description: "Set to true if PR fixup failed"
    value: ${{ steps.checkout.outputs.checkout_fail_pr_fixup }}

# Behaviour:
# If a PR is associated with the ref, it is used:
# - The history is rebased into the target branch head (fail -> checkout_fail_pr_rebase)
# - Fixup commits are auto squashed (fail -> checkout_fail_pr_fixup)
# If no PR is associated, just checkout N commits.

runs:
  using: composite
  steps:
    - name: Resolve ref to pr number and merge commit sha
      id: resolve
      shell: bash
      run: |
        # Resolve ref to pr number and merge commit sha
        [[ "${{ runner.debug }}" == "1" ]] && set -x

        ref="${{ inputs.ref }}"
        repository="${{ inputs.repository }}"

        branch=
        resp=
        pr_json=
        pr=

        if [[ "${{ inputs.repository }}" =~ ^(git@|ssh://|https://) ]]; then
          exit 0
        fi

        if ! [[ "$ref" =~ ^([0-9]+|pull/[0-9]+)(/head)?$ ]]; then
          # branch/commit

          # try branch
          branch="${ref#refs/heads/}"
          [[ "$branch" == *":"* ]] || {
            owner="${repository%/*}"
            branch="$owner:$branch"
          }
          # some-user:my-fix
          resp=$(curl -s \
            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$repository/pulls?head=$branch&state=open")

          pr_json=$(echo "$resp" | jq '.[0]')
          if [[ "$pr_json" == "null" ]]; then
            # try sha
            sha="$ref"
            resp=$(curl -s \
              -H "Authorization: Bearer ${{ inputs.gh-token }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$repository/commits/$sha/pulls")
            pr_json=$(echo "$resp" | jq '.[0]')
          fi

          pr=$(echo "$pr_json" | jq -r '.number')
          if [[ "$pr" == "null" ]]; then
            pr=""
          fi
        else
          # pr number
          pr="${ref#pull/}"
          pr="${pr%/head}"
        fi

        if [[ -n "$pr" ]]; then
          resp=$(curl -s \
            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$repository/pulls/$pr")
          status=$(echo "$resp" | jq -r '.status // empty')
          if [[ "$status" == "404" ]]; then
            # does not exist
            pr=""
          else
            merge_commit_sha=$(echo "$resp" | jq -r '.merge_commit_sha')
            if [[ "$merge_commit_sha" == "null" ]]; then
              # has conflicts
              merge_commit_sha=""
              pr=""
            fi
          fi
        fi

        echo "merge_commit_sha=$merge_commit_sha" >> "$GITHUB_OUTPUT"
        echo "pr=$pr" >> "$GITHUB_OUTPUT"
        echo "pr=$pr" >> "$GITHUB_ENV"

    - name: Prepare git
      shell: bash
      run: |
        # Prepare git
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        mkdir -p "${{ inputs.path }}" ; cd "${{ inputs.path }}"
        if command -v git-lfs >/dev/null 2>&1; then
          if [ "${{ inputs.lfs }}" = "true" ]; then
            git lfs install
          else
            git lfs install --skip-smudge
          fi
        elif [ "${{ inputs.lfs }}" = "true" ]; then
          echo "::warning ::Git LFS set to true, but git-lfs is not installed."
        fi
        if [[ "${{ inputs.repository }}" =~ ^(git@|ssh://|https://) ]]; then
          url="${{ inputs.repository }}"
          org_repository=$(echo "${{ inputs.repository }}" | sed -E 's|.*[:/]([^/]+/[^/.]+)(\.git)?$|\1|')
        else
          url="https://x-access-token:${{ inputs.gh-token }}@github.com/${{ inputs.repository }}.git"
          org_repository="${{ inputs.repository }}"
        fi

        if [[ -f .git/shallow.lock ]] || [[ -f .git/index.lock ]]; then
          rm -rf -- ..?* .[!.]* *
        fi

        if [[ ! -d .git ]]; then
          echo "git init"
          git init --initial-branch=trunk .
          git config core.pager cat
          git remote add origin "$url"
          local_ref="/mnt/git/$org_repository.git"
          if [[ -d $local_ref ]]; then
            git remote add local "file://$local_ref"
            git fetch local --depth 10
            git remote rm local
          fi
        else
          echo "git reset"
          git config core.pager cat
          git remote set-url origin "$url"

          git am --abort 2>/dev/null || true
          git merge --abort 2>/dev/null || true
          git rebase --abort 2>/dev/null || true
          git revert --abort 2>/dev/null || true
          git cherry-pick --abort 2>/dev/null || true
          git bisect reset 2>/dev/null || true
          git stash clear || true

          git reset --hard --quiet
          git clean -ffdx --quiet .

          git switch -d 2>/dev/null || true
          echo "clean-up branches"
          branches=$((git branch || true) | (grep -v ^'*' || true))
          if [[ "$branches" ]]; then
            git branch -D $branches || true
          fi
        fi

        git switch -C trunk

        if [[ -z "$(git config user.name)"  ]]; then
          git config user.name "github-actions[bot]"
        fi
        if [[ -z "$(git config user.email)"  ]]; then
          git config user.email "github-actions[bot]@users.noreply.github.com"
        fi
        git config gc.auto 0
        git config http.postBuffer 157286400

    - name: Checkout
      id: checkout
      shell: bash
      run: |
        # Checkout
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        cd "${{ inputs.path }}"

        repository="${{ inputs.repository }}"
        pr="${{ steps.resolve.outputs.pr }}"
        merge_commit_sha="${{ steps.resolve.outputs.merge_commit_sha }}"

        # --empty was added on git 2.26.0
        has_keep=$(git rebase -help 2>&1 | grep "\--empty" | wc -l) || true
        if [[ "$has_keep" -gt "0" ]]; then
          keep_empty="--empty=keep"
        else
          keep_empty="--keep-empty"
        fi

        fetch_depth=7

        git_fetch_deepen () {
          echo "fetch $fetch_depth commits"
          git fetch origin --deepen=$fetch_depth "$1"
          fetch_depth=$((fetch_depth * 2))
          [[ $fetch_depth -gt 500 ]] && fetch_depth=500 || true
        }
        if [[ -n "$pr" ]]; then
          mode="pr"
          # use merge commit sha because refs/pull/*/merge exist only on open pr
          git fetch origin --depth=1 "$merge_commit_sha"
          fetch_head=$(git rev-parse FETCH_HEAD)

          while ! git merge-base $fetch_head^1 $fetch_head^2 2>/dev/null ; do
            git_fetch_deepen "$fetch_head"
          done

          head_sha=$(git rev-parse $fetch_head^2)
          into_head_sha=$(git rev-parse $fetch_head^1)
          base_sha=$(git rev-list --reverse $into_head_sha..$head_sha | head -n 1)
          base_sha=$(git rev-parse $base_sha~)
        else
          mode="branch"
          if [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && \
             [[ "${{ github.event.forced }}" == "false" ]] && \
             [[ "${{ inputs.ref }}" == "${{ github.sha }}" ]]; then
            head_sha="${{ github.sha }}"
            base_sha="${{ github.event.before }}"
            while ! git rev-list --count $base_sha~..$head_sha 2>/dev/null ; do
              git_fetch_deepen "${{ inputs.ref }}"
            done
          else
            git fetch origin --depth=$fetch_depth "${{ inputs.ref }}"
            head_sha=$(git rev-parse "${{ inputs.ref }}")
            base_sha=$(git rev-parse $head_sha~$fetch_depth)
          fi
        fi

        git reset --hard FETCH_HEAD

        if [[ "$mode" == "pr" ]]; then
          # rebase into
          git rebase --rebase-merges "$keep_empty" \
            "$into_head_sha" "$head_sha" && {
            head_sha=$(git rev-parse HEAD)
            base_sha=$into_head_sha
          } || {
            git rebase --abort
            echo "checkout_fail_pr_rebase=true" >> "$GITHUB_ENV"
            echo "checkout_fail_pr_rebase=true" >> "$GITHUB_OUTPUT"
          }

          # apply fixups
          git log --oneline --pretty=format:'%s' $base_sha..$head_sha | grep ^fixup! && {
            git rebase $keep_empty --rebase-merges --autosquash $base_sha \
              || git rebase --abort && {
              head_sha=$(git rev-parse HEAD)
            } || {
              git rebase --abort
              echo "checkout_fail_pr_fixup=true" >> "$GITHUB_ENV"
              echo "checkout_fail_pr_fixup=true" >> "$GITHUB_OUTPUT"
            }
          } || true
        fi

        git log --oneline --reverse $base_sha..$head_sha

        git branch -m $branch 2>/dev/null || true

        echo "head_sha=$head_sha" >> "$GITHUB_OUTPUT"
        echo "base_sha=$base_sha" >> "$GITHUB_OUTPUT"
        echo "head_sha=$head_sha" >> "$GITHUB_ENV"
        echo "base_sha=$base_sha" >> "$GITHUB_ENV"

    - name: Finish
      shell: bash
      run: |
        # Finish
        git config --unset gc.auto
        git config --unset http.postBuffer
