FROM opensuse/leap:16.0

ENV version=v2
ARG runner_version=2.331.0
ARG runner_version_sha=5fcc01bd546ba5c3f1291c2803658ebd3cedb3836489eda3be357d41bfcf28a7
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh

RUN zypper update -y
RUN zypper install -y --no-recommends \
    tar gzip curl jq libicu coreutils

RUN useradd -m runner

USER runner
RUN mkdir -p /home/runner/actions-runner
WORKDIR /home/runner/actions-runner

RUN curl -o actions-runner.tar.gz -L https://github.com/actions/runner/releases/download/v${runner_version}/actions-runner-linux-x64-${runner_version}.tar.gz && \
    echo "${runner_version_sha} actions-runner.tar.gz" | sha256sum -c && \
    tar xzf actions-runner.tar.gz && rm actions-runner.tar.gz
RUN ./externals/node20/bin/node ./externals/node20/lib/node_modules/npm/bin/npm-cli.js --prefix ./externals/node20 -g update
RUN ./externals/node24/bin/node ./externals/node24/lib/node_modules/npm/bin/npm-cli.js --prefix ./externals/node24 -g update
RUN rm -r ../.npm ./externals/node*_alpine

USER root

#user: bash-completion openssh
#core: wget make git openssl ca-certificates ca-certificates-mozilla
#packaging: unzip
#weasyprint: libpango fontconfig lato-fonts
RUN zypper install -y --no-recommends \
    bash-completion openssh \
    wget make git openssl openssl-devel ca-certificates ca-certificates-mozilla \
    unzip xz \
    libpango-1_0-0 fontconfig lato-fonts

# git-lfs: install latest, dangerously bundles go packages.
ARG git_lfs_version=3.7.1
ARG git_lfs_version_sha=1c0b6ee5200ca708c5cebebb18fdeb0e1c98f1af5c1a9cba205a4c0ab5a5ec08
RUN curl -o git-lfs.tar.gz -L https://github.com/git-lfs/git-lfs/releases/download/v${git_lfs_version}/git-lfs-linux-amd64-v${git_lfs_version}.tar.gz && \
    echo "${git_lfs_version_sha} git-lfs.tar.gz" | sha256sum -c && \
    tar xzf git-lfs.tar.gz && rm git-lfs.tar.gz
RUN ./git-lfs-${git_lfs_version}/install.sh
RUN rm -r ./git-lfs-${git_lfs_version}

RUN update-ca-certificates
RUN fc-cache -f && fc-list

COPY ci/install-python.sh .
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.13.9 \
        3.13 \
        ed5ef34cda36cfa2f3a340f07cac7e7814f91c7f3c411f6d3562323a866c5c66
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.8.20 \
        3.8 \
        6fb89a7124201c61125c0ab4cf7f6894df339a40c02833bfd28ab4d7691fafb4
RUN update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python3.13 50
RUN rm install-python.sh

#bundle: nodejs npm
RUN zypper install -y --no-recommends \
    nodejs npm

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx entrypoint.sh

RUN git config --add --system user.name "CSE CI" ; \
    git config --add --system user.email "cse-ci-notifications@analog.com" ; \
    git config --add --system init.defaultBranch  "__runner_init_branch" ; \
    git config --add --system advice.mergeConflict false ; \
    git config --add --system advice.detachedHead false ; \
    git config --add --system fetch.prune true ; \
    git config --add --system fetch.pruneTags true ; \
    git config --add --system safe.directory '*'

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]

