FROM opensuse/leap:15.6

ENV runner_labels=v1
ARG runner_version=2.323.0
ARG runner_version_sha=f1533c606d724c6f157335b1921fdff17f52ff57f22907f0b77f82862e9900f0
ARG github_api_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/v1/github-api.sh
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/v1/entrypoint.sh

RUN zypper install -y --no-recommends \
    tar gzip curl jq libicu coreutils sha3sum

RUN useradd -m runner

USER runner
RUN mkdir -p /home/runner/actions-runner
WORKDIR /home/runner/actions-runner

RUN curl -o actions-runner.tar.gz -L https://github.com/actions/runner/releases/download/v${runner_version}/actions-runner-linux-x64-${runner_version}.tar.gz && \
    echo "${runner_version_sha} actions-runner.tar.gz" | sha3sum -a 256 -c && \
    tar xzf actions-runner.tar.gz

USER root
COPY install-deps.sh .
RUN chmod +x install-deps.sh ; ./install-deps.sh
COPY install-python.sh .
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.13.2 \
        3.13 \
        4c2d9202ab4db02c9d0999b14655dfe5
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.8.20 \
        3.8 \
        745478c81d6382cf46b5e7ad89e56008

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${github_api_sh} .
ADD ${entrypoint_sh} .
RUN chmod +rx github-api.sh
RUN chmod +rx entrypoint.sh

USER runner

RUN git config --global user.name "CSE CI" ; \
    git config --global user.email "cse-ci-notifications@analog.com" ; \
    git config --global init.defaultBranch  "__runner_init_branch" ; \
    git config --global advice.mergeConflict false ; \
    git config --global advice.detachedHead false ; \
    git config --global core.pager cat ; \
    git config --global --add safe.directory '*'

RUN mkdir -p /home/runner/playground
WORKDIR /home/runner/playground

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

