FROM opensuse/leap:16.0

ENV version=v2
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh
ARG git_defaults_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/git-defaults.sh
ARG gh_actions_runner_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/gh-actions-runner.sh

RUN zypper update -y
RUN zypper install -y --no-recommends \
    tar unzip gzip curl jq libicu coreutils

RUN useradd -m runner
WORKDIR /home/runner

ADD ${gh_actions_runner_sh} .
RUN bash ./gh-actions-runner.sh ; rm ./gh-actions-runner.sh

#user: bash-completion openssh
#core: wget make git openssl ca-certificates ca-certificates-mozilla
#weasyprint: libpango fontconfig lato-fonts
RUN zypper install -y --no-recommends \
    bash-completion openssh \
    wget make git openssl openssl-devel ca-certificates ca-certificates-mozilla \
    xz libpango-1_0-0 fontconfig lato-fonts

COPY ci/install-git-lfs.sh .
RUN chmod +x install-git-lfs.sh ; \
    ./install-git-lfs.sh \
        9afaf60b9c47e96f031f86d04089ef2e0b79a1fa \
        c9af709654580451d9600ce67ed1a17fd674f39e60e89bc359c1f28984702116
RUN rm install-git-lfs.sh

RUN update-ca-certificates
RUN fc-cache -f && fc-list

COPY ci/install-python.sh .
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.13.9 \
        3.13 \
        ed5ef34cda36cfa2f3a340f07cac7e7814f91c7f3c411f6d3562323a866c5c66
RUN chmod +x install-python.sh ; \
    ./install-python.sh \
        3.8.20 \
        3.8 \
        6fb89a7124201c61125c0ab4cf7f6894df339a40c02833bfd28ab4d7691fafb4
RUN update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python3.13 50
RUN rm install-python.sh

#bundle: nodejs npm
RUN ln -s /home/runner/externals/node24/bin/node /usr/local/bin/node
RUN ln -s /home/runner/externals/node24/bin/node /usr/local/bin/node24
RUN ln -s /home/runner/externals/node24/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
RUN ln -s /home/runner/externals/node24/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm24

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx ./entrypoint.sh

ADD ${git_defaults_sh} .
RUN bash ./git-defaults.sh ; rm ./git-defaults.sh

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]

