name: Container Build
description: Build and upload container images to Cloudsmith

inputs:
  gh-token:
    description: 'GitHub Token'
    default: ${{ github.token }}
  organization:
    description: 'Organization name'
    required: true
  image-name:
    description: 'Image name, can be the repository name'
    required: true
  ref:
    description: 'Branch/tag ref checked-out'
    required: true
    default: 'refs/heads/main'
  sbom-cve:
    description: 'Generate SBOM assert CVEs'
    default: 'true'
  containerfile:
    description: 'Path to the Containerfile'
    required: true
  cloudsmith-api-key:
    description: 'Cloudsmith API Key'
    required: false
  cloudsmith-service-slug:
    description: 'Cloudsmith Service Slug for OIDC'
    required: false
  cloudsmith-namespace:
    description: 'Cloudsmith namespace'
    required: false
  cloudsmith-repository:
    description: 'Cloudsmith repository name for containers'
    required: false

outputs:
  image_archive:
    description: "Path to image archive"
    value: ${{ steps.get_vars.outputs.image_archive }}
  sbom_archive:
    description: "Path to sbom archive"
    value: ${{ steps.run_sbom.outputs.sbom_archive }}
  version:
    description: "Built version"
    value: ${{ steps.get_vars.outputs.version }}



runs:
  using: composite
  steps:
    - name: Detect engine
      shell: bash
      run: |
        # Detect engine
        if command -v docker &> /dev/null; then
          echo "container=docker" >> "$GITHUB_ENV"
        elif command -v podman &> /dev/null; then
          echo "container=podman" >> "$GITHUB_ENV"
        else
          echo "::error ::Neither podman nor docker is installed."
          exit 1
        fi

    - name: Extract version from Containerfile
      id: get_vars
      shell: bash
      run: |
        # Extract version from Containerfile
        if [[ ! -f "${{ inputs.containerfile }}" ]]; then
          echo "::error ::Containerfile not found at ${{ inputs.containerfile }}"
          exit 1
        fi

        # Try python version
        init_file="$(echo "${{ inputs.containerfile }}" | cut -d/ -f1)/__init__.py"
        if [[ -f "$init_file" ]]; then
          version=$(grep "^__version__" "$init_file" | sed -nE "s/^__version__[[:space:]]*=[[:space:]]*['\"]([^'\"]+)['\"]/\1/p" | head -1)
          if [[ -z "$version" ]]; then
            echo "::error ::Could not extract version from $init_file, is it set at '__version__'?"
            exit 1
          fi
        fi

        # Try container version
        [[ -z "$version" ]] && version=$(grep "^ENV runner_labels" ${{ inputs.containerfile }} | sed -n 's/.*ENV runner_labels.*,v\([^,]*\).*/\1/p' | head -1)
        if [[ -z "$version" ]]; then
          echo "::error ::Could not extract version from ${{ inputs.containerfile }}, is it set at 'runner_labels'?"
          exit 1
        fi
        echo "version=v$version" >> "$GITHUB_ENV"
        echo "version=v$version" >> "$GITHUB_OUTPUT"
        echo "version: v$version"
        image_name=$(echo "${{ inputs.image-name}}" | tr '-' '_')
        echo "image_name=$image_name" >> "$GITHUB_ENV"
        image_archive=$(mktemp -d)/$(echo $image_name | tr '/' '_').tar
        echo "image_archive=$image_archive" >> "$GITHUB_ENV"
        echo "image_archive=$image_archive" >> "$GITHUB_OUTPUT"
        echo "container name: $image_name:$version"

    - name: Build container
      shell: bash
      run: |
        # Build container
        $container build --tag $image_name:$version -f ${{ inputs.containerfile }} .

    - name: Save container
      shell: bash
      run: |
        # Save container
        $container save -o $image_archive $image_name:$version

    - name: Prepare SBOM tools
      shell: bash
      if: ${{ inputs.sbom-cve == 'true' }}
      run: |
        # Prepare SBOM tools
        get_tools() {
          command -v syft || curl -sSfL https://get.anchore.io/syft | $1 sh -s -- -b /usr/local/bin
          command -v grype || curl -sSfL https://get.anchore.io/grype | $1 sh -s -- -b /usr/local/bin
        }

        if [ "$(id -u)" -eq 0 ]; then
          get_tools
        elif command -v sudo && sudo -n true 2>/dev/null; then
          get_tools "sudo"
        else
          command -v syft
          command -v grype
        fi

    - name: Run SBOM tools
      id: run_sbom
      shell: bash
      if: ${{ inputs.sbom-cve == 'true' }}
      run: |
        # Run SBOM tools
        run_sbom_tools () {
          pushd $1
          syft --from file -o cyclonedx-json -o table "$2" > .sbom
          head -n 1 .sbom > sbom.json

          grype db update
          grype -o json -o table \
                --fail-on high \
                --sort-by severity \
                sbom:sbom.json > .cves ; echo $? > .cves_ret
          head -n 1 .cves > cves.json
          zip $(dirname $2)/sbom.zip *
          echo "sbom_archive=$(dirname $2)/sbom.zip" >> $GITHUB_ENV
          echo "sbom_archive=$(dirname $2)/sbom.zip" >> $GITHUB_OUTPUT
          popd
        }

        assert_sbom() {
          pushd $1
          echo "CVEs:"$'\n'\`\`\`$'\n'"$(tail -n +2 .cves)"$'\n'"\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "SBOM:"$'\n'\`\`\`$'\n'"$(tail -n +2 .sbom)"$'\n'"\`\`\`" >> $GITHUB_STEP_SUMMARY

          type=
          tail -n +2 .cves | grep Medium && { type=warning ; level=Medium ;}
          tail -n +2 .cves | grep High && { type=error ; level=High ;}
          [ -n "$type" ] && echo "::$type ::assert_cves: CVE of level $level detected."

          ret=$(cat .cves_ret)
          popd ; rm -r $1
          return "$ret"
        }

        _sbom=$(mktemp -d)
        run_sbom_tools $_sbom $image_archive
        assert_sbom $_sbom

    - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.4
      if: ${{ inputs.cloudsmith-service-slug != '' && inputs.cloudsmith-service-slug != ' ' }}
      with:
        oidc-namespace: ${{ inputs.cloudsmith-namespace }}
        oidc-service-slug: ${{ inputs.cloudsmith-service-slug }}
        oidc-auth-only: 'true'

    - name: Cloudsmith API Key
      shell: bash
      if: ${{ inputs.cloudsmith-service-slug == '' || inputs.cloudsmith-service-slug == ' ' }}
      run: |
        # Cloudsmith API Key
        CLOUDSMITH_API_KEY=$(echo "${{ inputs.cloudsmith-api-key }}" | xargs)
        echo "CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY" >> "$GITHUB_ENV"

    - name: Cloudsmith get assets
      if: ${{ env.CLOUDSMITH_API_KEY != '' }}
      shell: bash
      run: |
        # Cloudsmith get assets
        curl -s -H "Authorization: Bearer ${{ inputs.gh-token }}" -L -o cloudsmith-api.sh \
          https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/main/ci/cloudsmith-api.sh

    - name: Cloudsmith upload container and create package
      shell: bash
      if: ${{ env.CLOUDSMITH_API_KEY != '' }}
      run: |
        # Cloudsmith upload container and create package
        source ./cloudsmith-api.sh

        # push: refs/heads/<branch>
        # tag || release: refs/tags/<tag>
        # pull_request: refs/pull/<id>/merge
        tags_="${{ inputs.ref }}, on/${{ github.event_name }}"

        package_file=$(
          cs-package-upload ${{ env.CLOUDSMITH_API_KEY }} \
                            ${{ inputs.cloudsmith-namespace }} \
                            ${{ inputs.cloudsmith-repository }} \
                            $image_archive \
                            latest_package_file
        )

        cs-package-store-docker ${{ env.CLOUDSMITH_API_KEY }} \
                                ${{ inputs.cloudsmith-namespace }} \
                                ${{ inputs.cloudsmith-repository }} \
                                $package_file \
                                "$tags_"

    - name: Cloudsmith upload SBOM
      shell: bash
      if: ${{ inputs.sbom-cve == 'true' && env.CLOUDSMITH_API_KEY != '' }}
      run: |
        # Cloudsmith upload SBOM
        source ./cloudsmith-api.sh

        tags_="${{ inputs.ref }}, on/${{ github.event_name }}"

        sbom_file=$(
          cs-package-upload ${{ env.CLOUDSMITH_API_KEY }} \
                            ${{ inputs.cloudsmith-namespace }} \
                            ${{ inputs.cloudsmith-repository }} \
                            "$sbom_archive" \
                            latest_sbom_file
        )

        cs-package-store-raw ${{ env.CLOUDSMITH_API_KEY }} \
                             ${{ inputs.cloudsmith-namespace }} \
                             ${{ inputs.cloudsmith-repository }} \
                             $sbom_file \
                             "$image_name.sbom.zip" \
                             "$tags_" \
                             "$version"


