name: Container Build
description: Build and upload container images to Cloudsmith

inputs:
  image-name:
    description: 'Image name, for example, adi/<repository>'
    required: true
  sbom-cve:
    description: 'Generate SBOM assert CVEs'
    default: true
    type: boolean
  fail-on:
    description: 'Fail on vulnerability severity, options: negligible low medium high critical'
    default: 'high'
  containerfile:
    description: 'Path to the Containerfile'
    required: true

outputs:
  image_archive:
    description: "Path to image archive"
    value: ${{ steps.get_vars.outputs.image_archive }}
  sbom_archive:
    description: "Path to sbom archive"
    value: ${{ steps.run_sbom.outputs.sbom_archive }}
  version:
    description: "Built version"
    value: ${{ steps.get_vars.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect engine
      shell: bash
      run: |
        # Detect engine
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        if command -v docker &> /dev/null; then
          echo "container=docker" >> "$GITHUB_ENV"
        elif command -v podman &> /dev/null; then
          echo "container=podman" >> "$GITHUB_ENV"
        else
          echo "::error ::Neither podman nor docker is installed."
          exit 1
        fi

    - name: Prepare name and version from context
      id: get_vars
      shell: bash
      run: |
        # Prepare name and version from context
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        if [[ ! -f "${{ inputs.containerfile }}" ]]; then
          echo "::error ::Containerfile not found at ${{ inputs.containerfile }}"
          exit 1
        fi

        # Try python version
        init_file="$(echo "${{ inputs.containerfile }}" | cut -d/ -f1)/__init__.py"
        if [[ -f "$init_file" ]]; then
          version=$(grep "^__version__" "$init_file" | sed -nE "s/^__version__[[:space:]]*=[[:space:]]*['\"]([^'\"]+)['\"]/\1/p" | head -1 || true)
          if [[ -z "$version" ]]; then
            echo "::error ::Could not extract version from $init_file, is it set at '__version__'?"
            exit 1
          else
            version=v$version
          fi
        fi

        # Try container version
        [[ -z "$version" ]] && version=$(grep "^ENV version" ${{ inputs.containerfile }} | sed -n 's/.*ENV version=\(.*\)/\1/p' | head -1 || true)
        [[ -z "$version" ]] && version=$(grep "^ENV runner_labels" ${{ inputs.containerfile }} | sed -n 's/.*ENV runner_labels.*,v\([^,]*\).*/v\1/p' | head -1 || true)
        if [[ -z "$version" ]]; then
          echo "::error ::Could not extract version from ${{ inputs.containerfile }}, is it set at 'version' (or old 'runner_labels')?"
          exit 1
        fi
        echo "version=$version" >> "$GITHUB_ENV"
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "version: $version"
        image_name="$(echo "${{ inputs.image-name }}" | tr '-' '_')"
        echo "image_name=$image_name" >> "$GITHUB_ENV"
        image_archive="$(mktemp -d)/$(echo $image_name | tr '/' '_').tar"
        echo "image_archive=$image_archive" >> "$GITHUB_ENV"
        echo "image_archive=$image_archive" >> "$GITHUB_OUTPUT"
        echo "container name: $image_name:$version"

    - name: Build container
      shell: bash
      run: |
        # Build container
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        $container build --tag $image_name:$version -f ${{ inputs.containerfile }} .

    - name: Save container
      shell: bash
      run: |
        # Save container
        $container save -o $image_archive $image_name:$version

    - name: Prepare SBOM tools
      shell: bash
      if: ${{ inputs.sbom-cve }}
      run: |
        # Prepare SBOM tools
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        get_tools() {
          command -v syft || curl -sSfL https://get.anchore.io/syft | $1 sh -s -- -b /usr/local/bin
          command -v grype || curl -sSfL https://get.anchore.io/grype | $1 sh -s -- -b /usr/local/bin
        }

        if [ "$(id -u)" -eq 0 ]; then
          get_tools
        elif command -v sudo && sudo -n true 2>/dev/null; then
          get_tools "sudo"
        else
          command -v syft
          command -v grype
        fi

    - name: Run SBOM tools
      id: run_sbom
      shell: bash
      if: ${{ inputs.sbom-cve }}
      run: |
        # Run SBOM tools
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        run_sbom_tools () {
          pushd $1
          syft --from file -o cyclonedx-json -o table "$2" > .sbom
          head -n 1 .sbom > sbom.json

          grype db update
          grype -o json -o table \
                --fail-on "${{ inputs.fail-on }}" \
                --sort-by severity \
                sbom:sbom.json > .cves || cves_ret=$?
          head -n 1 .cves > cves.json
          sbom_archive="$(dirname $2)/$(echo $image_name | tr '/' '_').sbom.zip"
          zip $sbom_archive * # No hidden files
          echo "sbom_archive=$sbom_archive" >> $GITHUB_ENV
          echo "sbom_archive=$sbom_archive" >> $GITHUB_OUTPUT
          popd
          return $cves_ret
        }

        assert_sbom() {
          pushd $1
          echo "CVEs:"$'\n'\`\`\`$'\n'"$(tail -n +2 .cves)"$'\n'"\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "SBOM:"$'\n'\`\`\`$'\n'"$(tail -n +2 .sbom)"$'\n'"\`\`\`" >> $GITHUB_STEP_SUMMARY

          type=
          tail -n +2 .cves | grep Medium && { type=warning ; level=Medium ;}
          tail -n +2 .cves | grep High && { type=error ; level=High ;}
          tail -n +2 .cves | grep Critical && { type=error ; level=Critical ;}
          [ -n "$type" ] && echo "::$type ::assert_cves: CVE of level $level detected."

          popd ; rm -r $1
          return $2
        }

        _sbom=$(mktemp -d)
        run_sbom_tools $_sbom $image_archive && \
          assert_sbom $_sbom $? || \
          assert_sbom $_sbom $?

