on: workflow_call
jobs:
  build-doc-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        pip install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip install dist/adi_doctools-*.tar.gz

    - name: Build doc
      working-directory: docs
      run: >
        ADOC_DOC_VERSION=${{ github.ref_name }}
        make html SPHINXOPTS='-W --keep-going' ;
        rm -rf _build/html/_sources

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: docs/_build/html

    - name: Check if new tag
      run: |
        tag=v$(sed -n 's/^__version__ = "\(.*\)"/\1/p' adi_doctools/__init__.py)
        git fetch --tags
        if ! [ $(git tag -l "$tag") ] ; then
          echo "new_tag=1" >> "$GITHUB_ENV"
        fi

    - name: Build tagged doc
      if: ${{ env.new_tag == '1' }}
      working-directory: docs
      run: >
        ADOC_TARGET_DEPTH=1
        ADOC_DOC_VERSION=$tag
        make clean html SPHINXOPTS='-W --keep-going' ;
        rm -rf _build/html/_sources

    - name: Store the generated tagged doc
      if: ${{ env.new_tag == '1' }}
      uses: actions/upload-artifact@v4
      with:
        name: html-tagged
        path: docs/_build/html

  build-doc-min:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        pip install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip install dist/adi_doctools-*.tar.gz

    - name: Build doc
      working-directory: docs
      run: |
        make html SPHINXOPTS='-W --keep-going'
        rm -rf _build/html/_sources

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html-min
        path: docs/_build/html
