on: workflow_call
jobs:
  build:
    runs-on: [self-hosted, v1]

    steps:
    - uses: actions/checkout@v4
      if: ${{ !env.ACT }}

    - name: act-checkout
      if: ${{ env.ACT }}
      run: |
        github_ref_name=$(cd /mnt/repo ; git rev-parse --abbrev-ref HEAD)
        git clone /mnt/repo --branch=$github_ref_name .

    - name: Install bundler dependencies
      run: >-
        npm install
        rollup
        @rollup/plugin-terser
        sass

    - name: Bundle web scripts
      run: >-
        node_modules/.bin/rollup -c
        ci/rollup.config.app.mjs

    - name: Bundle web styles
      run: >-
        node_modules/.bin/sass
        adi_doctools/theme/cosmic/style/app.bundle.scss:adi_doctools/theme/cosmic/static/app.min.css
        adi_doctools/theme/cosmic/style/extra.bundle.scss:adi_doctools/theme/cosmic/static/extra.min.css
        --style compressed

    - name: Fetch third-party fonts
      run: |
        ./ci/fetch-fonts.sh

    - name: Build a binary wheel and a source tarball
      run: |
        python3.13 -m venv ~/venv
        source ~/venv/bin/activate
        pip3.13 install build
        python3.13 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
