on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-doc-latest:
    runs-on: [self-hosted, v1]

    steps:
    - uses: analogdevicesinc/doctools/checkout@action

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        python3.13 -m venv venv/3.13/build-doc-latest
        source ./venv/3.13/build-doc-latest/bin/activate
        pip3.13 install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip3.13 install dist/*.tar.gz

    - name: Build doc
      working-directory: docs
      run: >
        source ../venv/3.13/build-doc-latest/bin/activate ;
        ADOC_DOC_VERSION=${{ inputs.tag }}
        make html SPHINXOPTS='-W --keep-going' ;
        rm -rf _build/html/_sources

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: docs/_build/html

  build-doc-min:
    runs-on: [self-hosted, v1]

    steps:
    - uses: analogdevicesinc/doctools/checkout@action

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        python3.8 -m venv venv/3.8/build-doc-min
        source ./venv/3.8/build-doc-min/bin/activate
        pip3.8 install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip3.8 install dist/*.tar.gz

    - name: Build doc
      working-directory: docs
      run: >
        source ../venv/3.8/build-doc-min/bin/activate ;
        make clean html SPHINXOPTS='-W --keep-going' ;
        rm -rf _build/html/_sources

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html-min
        path: docs/_build/html
