on: workflow_call
jobs:
  build-doc-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        pip install pip sphinx --upgrade
        pip install dist/adi-doctools-*.tar.gz

    - name: Build doc
      working-directory: docs
      run: |
        make html SPHINXOPTS='-W --keep-going'

    - name: Commit doc to gh-pages
      run: |
        author=$(git log -1 --pretty=format:'%an')
        email=$(git log -1 --pretty=format:'%ae')
        commit=$(git rev-parse --short HEAD)

        mkdir /tmp/doc
        rm -r docs/_build/html/_sources
        cp -r docs/_build/html/* /tmp/doc
        git stash --all
        git fetch origin gh-pages
        git checkout -b gh-pages origin/gh-pages
        git rm -r . --quiet
        cp -r /tmp/doc/* .
        touch .nojekyll

        git add . >> /dev/null
        git config --global user.name "$author"
        git config --global user.email "$email"
        git commit -m "deploy: $commit" --allow-empty

    - name: Push to gh-pages
      run: >-
        git push origin gh-pages:gh-pages

    - name: Clean-up
      run: >-
        rm -r /tmp/doc

  build-doc-min:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        pip install pip sphinx --upgrade
        pip install dist/adi-doctools-*.tar.gz

    - name: Build doc
      working-directory: docs
      run: |
        make html SPHINXOPTS='-W --keep-going'
