on: workflow_call
jobs:
  custom-doc:
    runs-on: [self-hosted, v1]

    steps:
    - uses: analogdevicesinc/doctools/checkout@v1

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        python3.13 -m venv ~/venv
        source ~/venv/bin/activate
        pip3.13 install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip3.13 install weasyprint
        pip3.13 install dist/adi_doctools-*.tar.gz

    - name: Prepare custom doc template
      working-directory: /tmp
      run: |
        mkdir -p my_pdf ; cd my_pdf
        mkdir -p custom-pages
        printf "Introduction\n============\n\n" > custom-pages/intro.rst
        yes "lorem ipsum dolor sit amet" 2>/dev/null | head -n 20 | tr '\n' ' ' >> custom-pages/intro.rst
        source ~/venv/bin/activate
        adoc custom-doc --builder pdf

    - name: Build custom doc
      working-directory: /tmp/my_pdf
      run: |
        export GIT_LFS_SKIP_SMUDGE=1
        source ~/venv/bin/activate
        adoc custom-doc --builder pdf

    - name: Store the generated pdf
      uses: actions/upload-artifact@v4
      with:
        name: custom-pdf
        path: /tmp/my_pdf/_build/output.pdf
