on: workflow_call
jobs:
  custom-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install pip packages
      run: |
        pip install $(tail --lines=+2 docs/requirements.txt) --upgrade
        pip install weasyprint sphinxcontrib.wavedrom matplotlib
        pip install dist/adi_doctools-*.tar.gz

    - name: Prepare custom doc template
      working-directory: /tmp
      run: |
        mkdir -p my_pdf ; cd my_pdf
        mkdir -p custom-pages
        printf "Introduction\n============\n\n" > custom-pages/intro.rst
        yes "lorem ipsum dolor sit amet" 2>/dev/null | head -n 20 | tr '\n' ' ' >> custom-pages/intro.rst
        adoc custom-doc --builder pdf --https

    - name: Build custom doc
      working-directory: /tmp/my_pdf
      run: |
        adoc custom-doc --builder pdf --https

    - name: Store the generated pdf
      uses: actions/upload-artifact@v4
      with:
        name: custom-pdf
        path: /tmp/my_pdf/_build/output.pdf
