on:
  workflow_call:
    inputs:
      asset_alias_name:
        required: true
        type: string
      asset_path:
        required: true
        type: string
      new_tag:
        required: true
        type: string
      tag:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  deploy-gh-pages:
    runs-on: [self-hosted, repo-only]
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/dev/gh-pages' || github.event_name == 'pull_request' }}

    steps:
    - uses: analogdevicesinc/doctools/gh-pages-deploy@action-gh-pages-deploy
      with:
        new_tag: ${{ inputs.new_tag }}
        tag: ${{ inputs.tag }}
        name: html
        path: ${{ github.ref_name }}

