name: Doc2vector
run-name: Doc2vector  ${{ inputs.repository }}@${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'Organization name'
        required: true
        type: string
        default: 'analogdevicesinc'
      repository:
        description: "Repository name"
        required: true
        type: string
      ref:
        description: "The branch, tag, SHA to resolve"
        required: true
        type: string
        default: 'gh-pages'
      forced:
        description: "Force pushed"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    concurrency:
      group: vector
      cancel-in-progress: false
    runs-on: [self-hosted, repo-only, v2]

    steps:
    - uses: analogdevicesinc/doctools/blank@action
      with:
        repository: ${{ github.repository }}
        path: vector

    - name: Clone target doc (cone)
      run: |
        # Filter out pulls|prs
        [[ -d "pages" ]] && rm -r "pages" || :
        url="https://x-access-token:${{ inputs.gh-token }}@github.com/${{ inputs.organization }}/${{ inputs.repository }}.git"
        git clone "$url" \
          --depth 1 \
          --filter=blob:none \
          --no-checkout \
          --branch ${{ inputs.ref }} -- pages

        cd pages
        git sparse-checkout init --cone
        sparse=$(git ls-tree --name-only -d "origin/${{ inputs.ref }}" | grep -Ev '^(pull|prs)')
        git sparse-checkout set $sparse
        git checkout "${{ inputs.ref }}"

    - name: Setup vector branch
      run: |
        cd vector
        git fetch origin vector --depth 1
        git switch -c vector FETCH_HEAD

    - name: Setup context
      run: |
        pages_base_sha=""
        [[ "${{ inputs.forced }}" == "true" ]] || \
          pages_base_sha="vector/${{ inputs.repository }}/commit"
        [[ -f "$pages_base_sha" ]] && \
          echo "pages_base_sha=$(cat $pages_base_sha)" >> $GITHUB_ENV || \
          echo "pages_base_sha=" >> $GITHUB_ENV

    - name: Setup remote ref
      run: |
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        cd pages
        git fetch origin --depth 1 "${{ inputs.ref }}"
        pages_head_sha=$(git rev-parse FETCH_HEAD)
        git switch -c pages FETCH_HEAD

        fetch_depth=5

        git_fetch_deepen () {
          echo "fetch $fetch_depth commits"
          git fetch origin --deepen=$fetch_depth "$1"
          fetch_depth=$((fetch_depth * 2))
          [[ $fetch_depth -gt 500 ]] && fetch_depth=500 || true
        }

        if [[ -n "$pages_base_sha" ]]; then
          while ! git rev-list --count $pages_base_sha~..$pages_head_sha ; do
            git_fetch_deepen "$pages_head_sha"
          done
        fi

        echo "pages_head_sha=$pages_head_sha" >> $GITHUB_ENV

    - name: Get touched versions
      run: |
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        cd pages

        if [[ -n "$pages_base_sha" ]]; then
          files=$(git diff --diff-filter=ACM --no-renames --name-only "$pages_base_sha~..$pages_head_sha")
        fi

        built_docs=$(find . -name objects.inv -exec sh -c 'dirname {}' ';' | sed 's|^\./||; s|^$|.|')
        if [[ -n "$files" ]]; then
          versions=$(
            for file in $files; do
              _version="${file%%/*}"
              if echo "$built_docs" | grep -Fxq "$_version"; then
                echo "$_version"
              else
                echo "."
              fi
          done | sort -u)
        else
          versions="$built_docs"
        fi

        echo "versions<<EOF" >> $GITHUB_ENV
        echo "$versions" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "built_docs<<EOF" >> $GITHUB_ENV
        echo "$built_docs" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Ensure node
      shell: bash
      run: |
        if ! which node ; then
          if [[ -d "/home/runner/externals/node24/bin" ]]; then
            echo "/home/runner/externals/node24/bin" >> "$GITHUB_PATH"
          elif [[ -d "/home/runner/externals/node20/bin" ]]; then
            echo "/home/runner/externals/node20/bin" >> "$GITHUB_PATH"
          fi
        fi

    - name: Setup WASM
      run: |
        source <(
          curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 https://raw.githubusercontent.com/analogdevicesinc/doctools/${{ github.ref }}/.github/scripts/ensure_turboquant_wasm.sh
        )
        ensure_turboquant_wasm

    - name: Setup tools
      run: |
        py_venv=$(mktemp -d)
        python3 -m venv "$py_venv"
        source "$py_venv/bin/activate"
        python3 -m ensurepip
        pip install https://github.com/analogdevicesinc/doctools/releases/download/pre-release/adi-doctools.tar.gz
        pip install sentence_transformers wasmtime

        echo "py_venv=$py_venv" >> $GITHUB_ENV

    - name: Vectorize versions
      run: |
        source "$py_venv/bin/activate"

        for version in $versions; do
          adoc doc2vector \
            --wasm $HOME/.local/share/turboquant.wasm \
            --docs pages \
            --version $version \
            --output vector/${{ inputs.repository }}/$version
        done

        echo "$pages_head_sha" > vector/${{ inputs.repository }}/commit

    - name: Remove stale versions
      run: |
        cd vector/${{ inputs.repository }}

        built_vectors=$(find . -name passages.json -exec sh -c 'dirname {}' ';' | sed 's|^\./||; s|^$|.|')

        stale_versions=$(comm -23 <(echo "$built_vectors" | sort) <(echo "$built_docs" | sort))

        for version in $stale_versions; do
          git rm -r "$version"
        done

    - name: Commit and push
      run: |
        cd vector
        git add .
        git commit -m "deploy: ${{ inputs.repository }}@${{ env.pages_head_sha }}"
        git push origin HEAD:vector

    - name: Clean-up
      if: always()
      run: |
        rm -rf "$py_venv"
        rm -rf "pages"
        rm -rf "vector"
