on:
  pull_request:
    types: [closed]

jobs:
  clean-gh-pages:
    runs-on: [self-hosted, v1]
    permissions:
      contents: write
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
    - uses: analogdevicesinc/doctools/blank@action

    - name: Clean-up gh-pages branch
      run: >
        git ls-remote --exit-code --heads origin refs/heads/gh-pages &&
        (
          git fetch origin gh-pages:gh-pages -f ;
          git switch gh-pages ;
          git rm -r pull/${{ github.event.number }} --quiet || true ;
          echo "gh_pages_exist=true" >> "$GITHUB_ENV" ;
        )

    - name: Generate aux files
      if: ${{ env.gh_pages_exist == 'true' }}
      run: >
        touch .nojekyll ;
        find . -name objects.inv -exec sh -c 'dirname {}' ';' |
        cut -c 3- | sort -Vr |
        jq --raw-input . |
        jq --slurp . > tags.json

    - name: Commit and push to gh-pages
      if: ${{ env.gh_pages_exist == 'true' }}
      run: |
        git add . >> /dev/null
        git commit -m "deploy: ${GITHUB_SHA} #${{ github.event.number }} (${{ github.event.action }})" --allow-empty
        git push origin gh-pages:gh-pages
