on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-package:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
  build-doc:
    uses: ./.github/workflows/build-doc.yml
    needs: [build-package]
    secrets: inherit
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [build-doc]
    secrets: inherit
