on:
  push:
    branches:
      - main
      - dev
      - dev/*
  pull_request:

jobs:
  build-package:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
  build-doc:
    uses: ./.github/workflows/build-doc.yml
    needs: [build-package]
    secrets: inherit
  tests:
    uses: ./.github/workflows/tests.yml
    needs: [build-package]
    secrets: inherit
  custom-doc:
    uses: ./.github/workflows/custom-doc.yml
    needs: [build-package]
    secrets: inherit
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [build-package, build-doc, tests, custom-doc]
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      new_tag: ${{ needs.build-package.outputs.new_tag }}
      tag: ${{ needs.build-package.outputs.tag }}
